spring:
  application:
    name: dynamodb-demo
  cloud:
    aws:
      dynamodb:
        endpoint: http://localhost:8000
        table-prefix: 
      region: 
        static: ap-northeast-1
      credentials:
        access-key: dummy
        secret-key: dummy